---

- name: Install Neovim prerequisites
  ansible.builtin.apt:
    pkg: [build-essential, cmake, curl, gettext, ninja-build, unzip]

- name: Clone Neovim repository
  register: neovim_current_version
  ansible.builtin.git:
    repo: https://github.com/neovim/neovim.git
    dest: /src/neovim
    single_branch: true
    version: master
    force: true

- name: Install Neovim
  changed_when: neovim_current_version.changed is true
  ansible.builtin.shell: |-
    cd /src/neovim
    make CMAKE_BUILD_TYPE=RelWithDebInfo
    cd build
    cpack -G DEB
    dpkg -i nvim-linux64.deb

- name: Clone my configuration
  ansible.builtin.git:
    repo: git@github.com:julianorchard/init.lua.git
    dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.config/nvim/"
    version: main
    ssh_opts: -o StrictHostKeyChecking=no
    key_file: "{{ lookup('ansible.builtin.env', 'HOME') }}/.ssh/id_ed25519"
