---

- name: Remove old Go installation
  ansible.builtin.file:
    path: /usr/local/go
    state: absent

- name: Download and extract new Go installation
  ansible.builtin.unarchive:
    src: https://go.dev/dl/go{{ go_version }}.linux-amd64.tar.gz
    dest: /usr/local
    remote_src: true
