---

- name: Install NVM
  become_user: "{{ lookup('ansible.builtin.env', 'USER') }}"
  ansible.builtin.shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
  args:
    creates: "{{ lookup('ansible.builtin.env', 'HOME') }}/.nvm/nvm.sh"

- name: Use target Node version
  ansible.builtin.shell: >-
    [ -s "{{ lookup('ansible.builtin.env', 'HOME') }}/.nvm/nvm.sh" ] && . "{{ ansible_env.HOME }}/.nvm/nvm.sh"
    nvm use v{{ node_version }}
