---

- name: Check if cargo is installed
  ansible.builtin.shell: command -v cargo
  register: cargo_exists
  ignore_errors: true

- name: Download rustup installer
  changed_when: cargo_exists is failed
  ansible.builtin.get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    force: 'yes'

- name: Install Rust/Cargo
  changed_when: cargo_exists is failed
  ansible.builtin.command: /tmp/sh.rustup.rs -y
