#!/usr/bin/env ansible-playbook
---

- name: All
  hosts: localhost
  gather_facts: true
  become: true

  vars:
    go_version: 1.22.1
    node_version: 22.2.0
    awesome_version: 4.3
    slack_version: 4.39.95

  roles:
    - role: development
      tags: [development]
    - role: neovim
      tags: [neovim]
    - role: gui
      tags: [gui, apps-all]
    - role: apps
      tags: [apps, apps-all]
#
# vi: ft=yaml.ansible
