name: Dotfiles

on:
  push:
    branches:
      - main

jobs:

  update-readme:

    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run readme-index.py
        run: python ${{ GITHUB_WORKSPACE }}.bin/readme-details.py --action

      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          add: "."
          message: "docs: auto-update README"
